### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by pnoeric** [wearerequired/huh-wp-docs#12]
How do we handle help docs in multiple languages?

Perhaps it could look for `helpfile_DE.md`, and then fall back gracefully to just `helpfile.md` if it can't find something for the current language.

**Comment by swissspidy** [comment]
I think i18n is the responsibility of the one who implements it.

The easiest way would be to use something like `$urls[] = __( 'myurl', 'mytextdomain' )` in your plugin and then set the different URLs in the translation file. Or maybe `if ( 'de' === $lang ) { $docs = …; } else { … }`. Whatever floats your boat.

**Comment by neverything** [comment]
I agree with @swissspidy on this @pnoeric. We can easily handle this on a per site basis. One thing to keep in mind, or that we could somehow implement is the current users backend language as this is now available on the `wp-admin/profile.php` page.

I'm closing this for now and we will figure out a way once the first customer needs a different language as that would mean translating all the docs you want to show anyways.

**Comment by pnoeric** [comment]
Ah ok, I see what @swissspidy is suggesting, that works fine for me.
