### ISSUE TITLE
Image path

### ISSUE THREAD

**Issue by zu** [wearerequired/huh-wp-docs#14]
path to images seems to be relative to wp-admin.
Can/should a constant/variable/function be used or can it be changed to be plugin-relative.

This would make it possible to have the documentation function outside the plugin which might make it easier to to full-screen and internal links (see https://github.com/wearerequired/huh-wp-docs/issues/13 and https://github.com/wearerequired/huh-wp-docs/issues/15)

**Comment by neverything** [comment]
For now you will have to use the relative path to the plugin, since help docs should contain them imho:

`/wp-content/plugins/presence-help/help/images/<image>` will do the trick here.
