### ISSUE TITLE
Integration of contextual wp help

### ISSUE THREAD

**Issue by zu** [wearerequired/huh-wp-docs#16]
The existing default contextual WordPress help (upper right) should somehow be integrated so as the huh help is kind of extending the existing help and always mentioning the default contextual help.

Make use of existing functions like [add_help_tab](https://developer.wordpress.org/reference/classes/WP_Screen/add_help_tab/) and [get_help_sidebar()](https://developer.wordpress.org/reference/classes/wp_screen/get_help_sidebar/)

**Comment by neverything** [comment]
As mentioned in https://github.com/switchplus/presence-help/issues/2#issuecomment-309274193 I believe the default WP help is not that good and very broad.
