### ISSUE TITLE
REQUIREMENTS

### ISSUE THREAD

**Issue by zu** [wearerequired/huh-wp-docs#17]
Some generic requirements for the help for presence
just indirectly related to huh, but here as a reminder

* centrally managed and automatically updated
* option to have customer specific help documents
* possibility to integrate pictures and movies (youtube/vimeo/local)
* language sensitive with fallback to default language ( [preferred-languages](https://github.com/swissspidy/preferred-languages) )
* no duplication of existing WordPress help

**Comment by neverything** [comment]
@zu this is probably the wrong place for the issue, see https://github.com/switchplus/presence-help/issues/2
